### ISSUE TITLE
Unable to install using NEVIRALLER

### ISSUE THREAD

**Issue by zer0cha0s** [RAprogramm/neviraide-install#1]
 OS : Arch Linux x86_64 
 Kernel : 6.7.2-arch1-1 

I have followed your install instructions to get this up and running but ran into some issues with the installer. 
I was missing 2 dependencies which installed fine via your installer so all requirements are met as shown below.
![image](https://github.com/RAprogramm/neviraide-install/assets/21130965/11829a18-910d-4648-9266-4bff56086928)
I then moved onto the Update an Install command, this updated neovim but hangs after cloning the repo.
![image](https://github.com/RAprogramm/neviraide-install/assets/21130965/80c04163-7bd4-48fd-a52e-8498c8c2737b)

I've re-download the installer, provided the correct permission and tried this process again but it just gets stuck after the repository cloned successfully message. 

I also found that after Neovim nightly installed i can no longer run nvim, i'm getting a permission denied error.

Any suggestions on what i can check ?

**Comment by RAprogramm** [comment]
I will try to reproduce your situation on a virtual machine and then notify you

**Comment by RAprogramm** [comment]
you're right! i have the same problem
---

while i will fix this problem you can manually install NEVIRAIDE with neovim-nightly.
1. create file with name update_nvim.sh.
2. put this into file:
```sh
#!/bin/bash

# Colors definitions
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
BOLD=$(tput bold)
NORMAL=$(tput sgr0)

# Check if necessary applications are installed
if ! [ -x "$(command -v wget)" ]; then
	printf "\n${RED}wget not found in path. Please install it to continue!${NC}\n"
	exit
fi

if ! [ -x "$(command -v curl)" ]; then
	printf "\n${RED}curl not found in path. Please install it to continue!${NC}\n"
	exit
fi

if ! [ -x "$(command -v xmllint)" ]; then
	printf "\n${RED}xmllint not found in path. Please install it to continue!${NC}\n"
	exit
fi

if ! [ -x "$(command -v datediff)" ]; then
	printf "\n${RED}dateutils not found in path. Please install it to continue!${NC}\n"
	exit
fi

# Get newest Neovim Nightly info
wget https://github.com/neovim/neovim/releases/tag/nightly -q -O - >/tmp/nvim28dce75c-4317-4006-a103-8069d573e2b2
RESPONSE=$(wget https://github.com/neovim/neovim/releases/tag/nightly --save-headers -O - 2>&1)

if [[ "$RESPONSE" =~ 404\ Not\ Found ]]; then
	printf "${RED}Couldn't fetch newest Neovim Nighly info. Aborting...${NC}\n"
	exit
fi

# Variables
SHOW_PROMPT=0
CURR_NVIM_VER=$(nvim --version | head -n 1)
NEW_NVIM_VER=$(xmllint --html --xpath "//pre//code/node()" /tmp/nvim28dce75c-4317-4006-a103-8069d573e2b2 2>/dev/null | grep NVIM)
CURR_DATETIME_ISO=$(date --iso-8601=ns)
NEW_NVIM_VER_RELEASE_DATETIME_ISO=$(xmllint --html --xpath "string(//relative-time/@datetime)" /tmp/nvim28dce75c-4317-4006-a103-8069d573e2b2 2>/dev/null)
LAST_RELEASE_DATETIME_DIFF=$(datediff ${NEW_NVIM_VER_RELEASE_DATETIME_ISO} ${CURR_DATETIME_ISO} -f "%H hours %M minutes ago")

# Check if Neovim Nightly exists in repo
if [[ "$NEW_NVIM_VER" == "" ]]; then
	printf "\n${RED}Couldn't fetch latest Neovim Nightly version from github repo! Check if it exists. Aborting...${NC}\n"
	exit
fi

# Check if the current neovim version is the latest
if [[ "$CURR_NVIM_VER" == "$NEW_NVIM_VER" ]]; then
	printf "\n${RED}No new version of ${BOLD}Neovim Nightly${NORMAL}${RED} found!\n${NC}Last release: ${LAST_RELEASE_DATETIME_DIFF}\nAborting...\n"
	exit
fi

# If a newer version of Neovim Nightly found show prompt
if [[ CURR_NVIM_VER != NEW_NVIM_VER ]]; then
	printf "\n${GREEN}New ${BOLD}Neovim Nightly${NORMAL}${GREEN} version found!${NC}\n${CURR_NVIM_VER} -> ${BOLD}${NEW_NVIM_VER}${NORMAL}\nReleased: ${LAST_RELEASE_DATETIME_DIFF}\n\n"
	SHOW_PROMPT=1
fi

# Update function
update_neovim() {
	printf "${RED}Updating Neovim Nightly...${NC}\n"
	HTTPS_URL="https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage"
	CURL_CMD="curl -L -w http_code=%{http_code}"
	CURL_OUTPUT=$(${CURL_CMD} ${HTTPS_URL} -o /tmp/nvim)
	HTTP_CODE=$(echo "${CURL_OUTPUT}" | sed -e 's/.*\http_code=//')
	ERROR_MESSAGE=$(echo "${CURL_OUTPUT}" | sed -e 's/http_code.*//')

	if [[ ${HTTP_CODE} == 200 ]]; then
		chmod +x /tmp/nvim
		sudo cp /tmp/nvim /usr/local/bin
		sudo mv /tmp/nvim /usr/bin
		printf "${GREEN}Neovim Nightly has been updated successfully!${NC}\n"
	else
		printf "${RED}Neovim Nightly has NOT been updated! ERROR: ${ERROR_MESSAGE}${NC}\n"
	fi
}

rm /tmp/nvim28dce75c-4317-4006-a103-8069d573e2b2

while [ $SHOW_PROMPT -gt 0 ]; do
	read -p "Do you wish to update neovim? [yes/no] " yn
	case $yn in
	[Yy]*)
		update_neovim
		break
		;;
	[Nn]*) exit ;;
	*) echo "Please answer yes or no." ;;
	esac
done

```
3. Put `update_nvim.sh` to your `PATH` (this, perhaps, `/home/username/bin`) to call this script everywhere.
4. make `update_nvim.sh` executable (`chmod +x update_nvim.sh`) and run it in your terminal.
5. Clone repo NEVIRAIDE `git clone https://github.com/RAprogramm/NEVIRAIDE`
6. rename NEVIRAIDE to nvim (`mv NEVIRAIDE nvim`)
7. put `nvim` to `/home/username/.config/` 

---

i will try to fix problem with installer. Thank you

**Comment by zer0cha0s** [comment]
Thanks for taking the time to respond and help me get this working. 
I followed the steps provided and had no issues until i opened nvim and im facing this error : 
 
![image](https://github.com/RAprogramm/neviraide-install/assets/21130965/c661936a-e4cc-437d-9517-3c80fd5811af)

Few things i've tried : 
- clearing the .cache/nvim folder
- removing the nvim folder from config and cloning it again and following the steps to rename and move. 
- Ive checked the .local/share/nvim folder and neviraide_ui does not exist (Should this have been created as part of a plugin install on first start ?)

**Comment by RAprogramm** [comment]
> Thanks for taking the time to respond and help me get this working. 
> I followed the steps provided and had no issues until i opened nvim and im facing this error : 
>  
> ![image](https://github.com/RAprogramm/neviraide-install/assets/21130965/c661936a-e4cc-437d-9517-3c80fd5811af)
> 
> Few things i've tried : 
> - clearing the .cache/nvim folder
> - removing the nvim folder from config and cloning it again and following the steps to rename and move. 
> - Ive checked the .local/share/nvim folder and neviraide_ui does not exist (Should this have been created as part of a plugin install on first start ?)

This error indicates that there is no cache file 'defaults'.  this and similar files are generated to make the user interface load faster.  In theory, this should go away after downloading the plugins.
Try to `Lazy install` in neovim.
I will fix it to. Thank you

**Comment by RAprogramm** [comment]
> Thanks for taking the time to respond and help me get this working. I followed the steps provided and had no issues until i opened nvim and im facing this error :
> 
> ![image](https://private-user-images.githubusercontent.com/21130965/301551166-c661936a-e4cc-437d-9517-3c80fd5811af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjQxMDgsIm5iZiI6MTcwNjgyMzgwOCwicGF0aCI6Ii8yMTEzMDk2NS8zMDE1NTExNjYtYzY2MTkzNmEtZTRjYy00MzdkLTk1MTctM2M4MGZkNTgxMWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDIxNDMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZjQ3ODkwZWZmNzhjY2QwNDU1OGRlNDBkNmFiYTdhOTcyOTFjMjBiMDhlZDAyZTFkMzMyZGE1ZGU0YzYwZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qiy7hDTPYF0a3GfBqKVO5cZ1py2ii418zicfbrGEPGc)
> 
> Few things i've tried :
> 
>     * clearing the .cache/nvim folder
> 
>     * removing the nvim folder from config and cloning it again and following the steps to rename and move.
> 
>     * Ive checked the .local/share/nvim folder and neviraide_ui does not exist (Should this have been created as part of a plugin install on first start ?)

i fix it.
now you can try clone NEVIRAIDE and run it. 
1. First time enter nvim you will see installation core dependencies and ui plugin.
2. After it finished - close nvim.
3. Second time enter nvim you will see installation all another plugins.

[test-screen0.webm](https://github.com/RAprogramm/neviraide-install/assets/70325462/a1aaa185-72a7-428f-9977-0f46f0ed774f)

---

now i will fixing installer

**Comment by zer0cha0s** [comment]
That fixed it for me, thanks for your support. Going to go explore what Neviraide has to offer now. 
![image](https://github.com/RAprogramm/neviraide-install/assets/21130965/c9bafcbb-0388-42cb-bcf2-b8bbf7443777)

**Comment by RAprogramm** [comment]
> That fixed it for me, thanks for your support. Going to go explore what Neviraide has to offer now. ![image](https://private-user-images.githubusercontent.com/21130965/301661580-c9bafcbb-0388-42cb-bcf2-b8bbf7443777.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjYwMDQsIm5iZiI6MTcwNjgyNTcwNCwicGF0aCI6Ii8yMTEzMDk2NS8zMDE2NjE1ODAtYzliYWZjYmItMDM4OC00MmNiLWJjZjItYjhiYmY3NDQzNzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDIyMTUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZTQwNDdhMjYwMTBkYzA4YTAyNTcyZTM4ODU5MWVmN2E0MWE4NTJiOWMyNTBiMWIzN2JiMTlmMGFjOTZkMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XPcsf3R1KktSLE0oI35PF7z1sxCkim7DqW2sACwyk7E)

thanks for your attention.

BTW, i see wrong icons in your dashboard. 
NEVIRAIDE using nonicons, so you can install it by `yay -S nonicons-git` and then put this `symbol_map U+f101-U+f25c nonicons` into your kitty.conf

here is my kitty.conf, for example (i removed paddings for better view)

```conf
font_family JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

symbol_map U+f101-U+f25c nonicons
font_size 13
include themes/theme.conf
```

**Comment by zer0cha0s** [comment]
> BTW, i see wrong icons in your dashboard.

Nice spot, updated my conf and it looks even better now.
Thanks again.
